"""Persistence infrastructure."""

from app.infrastructure.persistence.database import (
    Base,
    DatabaseBootstrapper,
    Download,
    IgnoredTerm,
    LocalFolder,
    LocalSong,
    PlaylistComparison,
    PlaylistComparisonResult,
    SessionLocal,
    YoutubePlaylist,
    YoutubePlaylistItem,
    engine,
    get_session,
)
from app.infrastructure.persistence.repositories import (
    DownloadSqlAlchemyRepository,
    IgnoredTermSqlAlchemyRepository,
    LocalFolderSqlAlchemyRepository,
    LocalSongSqlAlchemyRepository,
    PlaylistComparisonResultSqlAlchemyRepository,
    PlaylistComparisonSqlAlchemyRepository,
    SqlAlchemyRepository,
    YoutubePlaylistItemSqlAlchemyRepository,
    YoutubePlaylistSqlAlchemyRepository,
)

__all__ = [
    "Base",
    "DatabaseBootstrapper",
    "Download",
    "DownloadSqlAlchemyRepository",
    "IgnoredTerm",
    "IgnoredTermSqlAlchemyRepository",
    "LocalFolder",
    "LocalFolderSqlAlchemyRepository",
    "LocalSong",
    "LocalSongSqlAlchemyRepository",
    "PlaylistComparison",
    "PlaylistComparisonResult",
    "PlaylistComparisonResultSqlAlchemyRepository",
    "PlaylistComparisonSqlAlchemyRepository",
    "SessionLocal",
    "SqlAlchemyRepository",
    "YoutubePlaylist",
    "YoutubePlaylistItem",
    "YoutubePlaylistItemSqlAlchemyRepository",
    "YoutubePlaylistSqlAlchemyRepository",
    "engine",
    "get_session",
]
