"""Playlists domain services."""

from app.domain.playlists.services.playlistItemMatcherService import (
    PlaylistItemMatchResult,
    matchYoutubePlaylistItemToLocalSongs,
)
from app.domain.playlists.services.matchDecisionSource import (
    AUTO_AMBIGUOUS,
    AUTO_NO_COMPETITIVE_CANDIDATE,
    AUTO_TITLE_ARTIST_DURATION,
    MANUAL_USER_LINKED_LOCAL_SONG,
    MANUAL_USER_MARKED_FOUND,
    MANUAL_USER_MARKED_MISSING,
    MANUAL_USER_MARKED_POSSIBLE,
    buildAutomaticMatchedBy,
    isAutomaticMatchedBy,
    isManualMatchedBy,
)
from app.domain.playlists.services.playlistItemMatchingRules import (
    AmbiguityPenaltyThresholds,
    ArtistMatchEvidence,
    CandidateMatchEvidence,
    CandidateScoreBreakdown,
    ConsistencyScoreWeights,
    DEFAULT_PLAYLIST_ITEM_MATCHING_RULESET,
    DurationMatchThresholds,
    DurationMatchEvidence,
    MatchClassificationThresholds,
    PlaylistItemMatchingRuleset,
    TextMatchWeights,
    TitleMatchEvidence,
    buildMatchReason,
    buildArtistMatchEvidence,
    buildCandidateMatchEvidence,
    buildDurationMatchEvidence,
    buildTextMatchEvidence,
    calculateAmbiguityPenalty,
    classifyMatchStatus,
    normalizedSimilarityRatio,
    scoreDuration,
    scoreEvidenceConsistency,
    scoreNormalizedText,
)
from app.domain.playlists.services.youtubePlaylistItemNormalizationService import (
    NormalizedYoutubePlaylistItemMetadata,
    normalizeYoutubePlaylistItemMetadata,
)

__all__ = [
    "DEFAULT_PLAYLIST_ITEM_MATCHING_RULESET",
    "AmbiguityPenaltyThresholds",
    "AUTO_AMBIGUOUS",
    "AUTO_NO_COMPETITIVE_CANDIDATE",
    "AUTO_TITLE_ARTIST_DURATION",
    "ArtistMatchEvidence",
    "CandidateMatchEvidence",
    "CandidateScoreBreakdown",
    "ConsistencyScoreWeights",
    "DurationMatchThresholds",
    "DurationMatchEvidence",
    "MANUAL_USER_LINKED_LOCAL_SONG",
    "MANUAL_USER_MARKED_FOUND",
    "MANUAL_USER_MARKED_MISSING",
    "MANUAL_USER_MARKED_POSSIBLE",
    "MatchClassificationThresholds",
    "PlaylistItemMatchResult",
    "PlaylistItemMatchingRuleset",
    "NormalizedYoutubePlaylistItemMetadata",
    "TextMatchWeights",
    "TitleMatchEvidence",
    "buildAutomaticMatchedBy",
    "buildMatchReason",
    "buildArtistMatchEvidence",
    "buildCandidateMatchEvidence",
    "buildDurationMatchEvidence",
    "buildTextMatchEvidence",
    "calculateAmbiguityPenalty",
    "classifyMatchStatus",
    "isAutomaticMatchedBy",
    "isManualMatchedBy",
    "matchYoutubePlaylistItemToLocalSongs",
    "normalizedSimilarityRatio",
    "normalizeYoutubePlaylistItemMetadata",
    "scoreDuration",
    "scoreEvidenceConsistency",
    "scoreNormalizedText",
]
