"""Playlists domain services."""

from app.domain.playlists.services.playlistItemMatcherService import (
    PlaylistItemMatchResult,
    matchYoutubePlaylistItemToLocalSongs,
)
from app.domain.playlists.services.playlistItemMatchingRules import (
    AmbiguityPenaltyThresholds,
    ArtistMatchEvidence,
    CandidateMatchEvidence,
    CandidateScoreBreakdown,
    ConsistencyScoreWeights,
    DEFAULT_PLAYLIST_ITEM_MATCHING_RULESET,
    DurationMatchThresholds,
    DurationMatchEvidence,
    MatchClassificationThresholds,
    PlaylistItemMatchingRuleset,
    TextMatchWeights,
    TitleMatchEvidence,
    buildMatchReason,
    buildArtistMatchEvidence,
    buildCandidateMatchEvidence,
    buildDurationMatchEvidence,
    buildTextMatchEvidence,
    calculateAmbiguityPenalty,
    classifyMatchStatus,
    normalizedSimilarityRatio,
    scoreDuration,
    scoreEvidenceConsistency,
    scoreNormalizedText,
)
from app.domain.playlists.services.youtubePlaylistItemNormalizationService import (
    NormalizedYoutubePlaylistItemMetadata,
    normalizeYoutubePlaylistItemMetadata,
)

__all__ = [
    "DEFAULT_PLAYLIST_ITEM_MATCHING_RULESET",
    "AmbiguityPenaltyThresholds",
    "ArtistMatchEvidence",
    "CandidateMatchEvidence",
    "CandidateScoreBreakdown",
    "ConsistencyScoreWeights",
    "DurationMatchThresholds",
    "DurationMatchEvidence",
    "MatchClassificationThresholds",
    "PlaylistItemMatchResult",
    "PlaylistItemMatchingRuleset",
    "NormalizedYoutubePlaylistItemMetadata",
    "TextMatchWeights",
    "TitleMatchEvidence",
    "buildMatchReason",
    "buildArtistMatchEvidence",
    "buildCandidateMatchEvidence",
    "buildDurationMatchEvidence",
    "buildTextMatchEvidence",
    "calculateAmbiguityPenalty",
    "classifyMatchStatus",
    "matchYoutubePlaylistItemToLocalSongs",
    "normalizedSimilarityRatio",
    "normalizeYoutubePlaylistItemMetadata",
    "scoreDuration",
    "scoreEvidenceConsistency",
    "scoreNormalizedText",
]
