from __future__ import annotations

THEME_TOKENS: dict[str, str] = {
    "FONT_FAMILY": "Inter, Segoe UI, sans-serif",
    "COLOR_BG": "#121212",
    "COLOR_PANEL": "#1B1B1B",
    "COLOR_SURFACE": "#242424",
    "COLOR_SURFACE_ALT": "#2D2D2D",
    "COLOR_BORDER": "#303030",
    "COLOR_TEXT": "#FFFFFF",
    "COLOR_TEXT_SECONDARY": "#D0D0D0",
    "COLOR_TEXT_DISABLED": "#8A8A8A",
    "COLOR_PRIMARY": "#D64545",
    "COLOR_PRIMARY_HOVER": "#C13A3A",
    "COLOR_ACCENT": "#5B8DEF",
    "COLOR_ACCENT_SOFT": "#263246",
    "COLOR_SUCCESS": "#3DA37C",
    "COLOR_SELECTION": "#2A2A2A",
    "SPACING_8": "8px",
    "SPACING_16": "16px",
    "SPACING_24": "24px",
    "SPACING_32": "32px",
    "RADIUS_8": "8px",
    "RADIUS_12": "12px",
}
